spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://sebas9:Halamadrid10@cluster0.2u8mg.mongodb.net/purely_product_service?retryWrites=true&w=majority&appName=Cluster0

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0 # Permitir que Railway asigne un puerto dinámico

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true # Usar IP en lugar de hostname
    metadata-map:
      management.context-path: /
  client:
    service-url:
      defaultZone: https://service-registry-production-8dd6.up.railway.app/eureka/
    register-with-eureka: true
    fetch-registry: true
